# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      EV1: app/abc

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 6
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo "EV1=$HOME/$EV1" >> $GITHUB_ENV
          echo Hello, world!
          echo "SHA=$SHA"
          echo SHA=$SHA

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo $EV1
          echo Add other actions to build,
          echo test, and deploy your project.
          mkdir -p $EV1
          echo "This is a message." > ${{ env.EV1 }}/testfile
          echo SHA=$SHA
          
      - uses: actions/upload-artifact@v2
        with:
          name: test-artifact
          path: ${{ env.EV1 }}/testfile
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn` 
